//Translates
export const t = {
    en: {
        h1:'Header 1 level',
        h2:'Header 2 level',
        h3:'Header 3 level',
        h4:'Header 4 level',
        h5:'Header 5 level',
        h6:'Header 6 level',
        span:'String',
        mark:'Marked text',
        small:'Small text',
        dfn:'Definition',
        a:'Link',
        q:'Inline quote',
        b:'Bold',
        i:'Italic',
        u:'Underlined',
        s:'Small',
        sup:'Superscript',
        sub:'Subscript',
        kbd:'Button',
        abbr:'Abbrevature',
        strong:'Important text',
        code:'Inline code',
        samp:'PC program output',
        del:'Deleted text from document',
        ins:'Insert text into document',
        var:'Variable designation',
        ul:'The bulleted list',
        ol:'Numbered list',
        pre:'Formatted text',
        time:'Date and time',
        img:'Image',
        audio:'Audio element',
        video:'Video element',
        blockquote:'Blockquote',
        clearFormat: 'Clear text format',
        toggleViewMode: 'Toggle view Text/HTML5',
        addNewParahraph: 'Add new parahraph',
        fullScreen: 'fullScreen',
        required: 'Field required',
        minlength: 'Min length is:',
        maxlength: 'Max length is:',
        filtertags: 'Found filter tag:',
    },
    ru: {
        h1:'Заголовок 1 уровня',
        h2:'Заголовок 2 уровня',
        h3:'Заголовок 3 уровня',
        h4:'Заголовок 4 уровня',
        h5:'Заголовок 5 уровня',
        h6:'Заголовок 6 уровня',
        span:'Строка',
        mark:'Помеченный текст',
        small:'Маленький текст',
        dfn:'Определение',
        a:'Ссылка',
        q:'Внутритекстовая цитата',
        b:'Жирный',
        i:'Курсив',
        u:'Подчеркнутый',
        s:'Маленький',
        sup:'Надстрочный',
        sub:'Подстрочный',
        kbd:'Кнопка',
        abbr:'Аббривеатура',
        strong:'Важный текст',
        code:'Внутритекстовый код',
        samp:'Вывод ПК программы',
        del:'Удаленный текст из документа',
        ins:'Вставленный текст в документ',
        var:'Обозначение переменной',
        ul:'Маркированный список',
        ol:'Нумерованный список',
        pre:'Форматированный текст',
        time:'Дата и время',
        img:'Изображение',
        audio:'Аудио элемент',
        video:'Видео элемент',
        blockquote:'Блок цитаты',
        clearFormat: 'Очистить формат',
        toggleViewMode: 'Переключить вид текст/html5',
        addNewParahraph: 'Добавить параграф',
        fullScreen: 'Полноэкранный режим',
        required: 'Обязательно для заполнения',
        minlength: 'Минимальная длинна:',
        maxlength: 'Максимальная длинна:',
        filtertags: 'Найден запрещенный тег:',
    }
};